name: BSD
on: [push, pull_request]

jobs:
  freebsd:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Build
      uses: vmactions/freebsd-vm@v1.0.2
      with:
        run: |
          pkg update
          pkg install -y autoconf automake bison flex pkgconf
          ./autogen.sh
          ./configure
          make
          make dist-xz
          make install
